
name: budget_app
description: A dashboard app with sidebar navigation and transitions.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.1.1
  dio: ^5.4.0
  intl: ^0.20.2
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.15.0
  flutter_secure_storage: ^9.0.0

  # Optional: Add packages here if needed, like provider, animations, etc.

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Optional: Add asset folders if needed in the future
  # assets:
  #   - assets/images/
